### ISSUE TITLE
Liste des études / projets

### ISSUE THREAD

**Issue by lpojgc** [dthonon/Client_API_VN#332]
Est-ce qu'il est possible de récupérer par l'API la lsite des études / projets ?

**Comment by dthonon** [comment]
Je n'ai pas vu d'API correspondante. Il faudrait l'ajouter à la liste des demandes d'évolution.

**Comment by dthonon** [comment]
Réponse de Gaëtan : 
Hi,
We have a route in the observer_controller.
We don’t promote that too much because it queries all portal and return the projects associated to that observer on all portal at once. That query is slow but it’s OK for NaturaList as it’s run in the background.
We have no route to get project lists on a given portal.
So, it’s probably not what you need but we will add a project_controller based on the protocol_controller in the future.
Thanks,
Gaëtan
